name: lint

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD:/repo" -w /repo rhysd/actionlint:latest -color
